/* Generated by Yosys 0.9+4052 (git sha1 d061b0e, gcc 8.3.1 -fPIC -Os) */

module lut_s44(addr, out, config_clk, config_en, config_in, config_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  input [6:0] addr;
  input config_clk;
  input config_en;
  input [7:0] config_in;
  output [7:0] config_out;
  wire \first_lut.mem[0] ;
  wire \first_lut.mem[10] ;
  wire \first_lut.mem[11] ;
  wire \first_lut.mem[12] ;
  wire \first_lut.mem[13] ;
  wire \first_lut.mem[14] ;
  wire \first_lut.mem[15] ;
  wire \first_lut.mem[1] ;
  wire \first_lut.mem[2] ;
  wire \first_lut.mem[3] ;
  wire \first_lut.mem[4] ;
  wire \first_lut.mem[5] ;
  wire \first_lut.mem[6] ;
  wire \first_lut.mem[7] ;
  wire \first_lut.mem[8] ;
  wire \first_lut.mem[9] ;
  output out;
  wire \second_lut.mem[0] ;
  wire \second_lut.mem[10] ;
  wire \second_lut.mem[11] ;
  wire \second_lut.mem[12] ;
  wire \second_lut.mem[13] ;
  wire \second_lut.mem[14] ;
  wire \second_lut.mem[15] ;
  wire \second_lut.mem[1] ;
  wire \second_lut.mem[2] ;
  wire \second_lut.mem[3] ;
  wire \second_lut.mem[4] ;
  wire \second_lut.mem[5] ;
  wire \second_lut.mem[6] ;
  wire \second_lut.mem[7] ;
  wire \second_lut.mem[8] ;
  wire \second_lut.mem[9] ;
  sky130_fd_sc_hd__inv_2 _049_ (
    .A(config_en),
    .Y(_042_)
  );
  sky130_fd_sc_hd__buf_1 _050_ (
    .A(_042_),
    .X(_043_)
  );
  sky130_fd_sc_hd__buf_1 _051_ (
    .A(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__o22a_2 _052_ (
    .A1(\first_lut.mem[6] ),
    .A2(_044_),
    .B1(\first_lut.mem[14] ),
    .B2(config_en),
    .X(_039_)
  );
  sky130_fd_sc_hd__o22a_2 _053_ (
    .A1(_044_),
    .A2(\first_lut.mem[5] ),
    .B1(config_en),
    .B2(\first_lut.mem[13] ),
    .X(_038_)
  );
  sky130_fd_sc_hd__o22a_2 _054_ (
    .A1(_044_),
    .A2(\first_lut.mem[4] ),
    .B1(config_en),
    .B2(\first_lut.mem[12] ),
    .X(_037_)
  );
  sky130_fd_sc_hd__o22a_2 _055_ (
    .A1(_044_),
    .A2(\first_lut.mem[3] ),
    .B1(config_en),
    .B2(\first_lut.mem[11] ),
    .X(_036_)
  );
  sky130_fd_sc_hd__buf_1 _056_ (
    .A(_043_),
    .X(_045_)
  );
  sky130_fd_sc_hd__o22a_2 _057_ (
    .A1(_045_),
    .A2(\first_lut.mem[2] ),
    .B1(config_en),
    .B2(\first_lut.mem[10] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__o22a_2 _058_ (
    .A1(_045_),
    .A2(\first_lut.mem[1] ),
    .B1(config_en),
    .B2(\first_lut.mem[9] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__o22a_2 _059_ (
    .A1(_045_),
    .A2(\first_lut.mem[0] ),
    .B1(config_en),
    .B2(\first_lut.mem[8] ),
    .X(_033_)
  );
  sky130_fd_sc_hd__o22a_2 _060_ (
    .A1(_045_),
    .A2(config_in[7]),
    .B1(config_en),
    .B2(\first_lut.mem[7] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__o22a_2 _061_ (
    .A1(_045_),
    .A2(config_in[6]),
    .B1(\first_lut.mem[6] ),
    .B2(config_en),
    .X(_031_)
  );
  sky130_fd_sc_hd__buf_1 _062_ (
    .A(_043_),
    .X(_046_)
  );
  sky130_fd_sc_hd__o22a_2 _063_ (
    .A1(_046_),
    .A2(config_in[5]),
    .B1(config_en),
    .B2(\first_lut.mem[5] ),
    .X(_030_)
  );
  sky130_fd_sc_hd__o22a_2 _064_ (
    .A1(_046_),
    .A2(config_in[4]),
    .B1(config_en),
    .B2(\first_lut.mem[4] ),
    .X(_029_)
  );
  sky130_fd_sc_hd__o22a_2 _065_ (
    .A1(_046_),
    .A2(config_in[3]),
    .B1(config_en),
    .B2(\first_lut.mem[3] ),
    .X(_028_)
  );
  sky130_fd_sc_hd__o22a_2 _066_ (
    .A1(_046_),
    .A2(config_in[2]),
    .B1(config_en),
    .B2(\first_lut.mem[2] ),
    .X(_027_)
  );
  sky130_fd_sc_hd__o22a_2 _067_ (
    .A1(_046_),
    .A2(config_in[1]),
    .B1(config_en),
    .B2(\first_lut.mem[1] ),
    .X(_026_)
  );
  sky130_fd_sc_hd__buf_1 _068_ (
    .A(_042_),
    .X(_047_)
  );
  sky130_fd_sc_hd__o22a_2 _069_ (
    .A1(_047_),
    .A2(config_in[0]),
    .B1(config_en),
    .B2(\first_lut.mem[0] ),
    .X(_025_)
  );
  sky130_fd_sc_hd__o22a_2 _070_ (
    .A1(_047_),
    .A2(\second_lut.mem[7] ),
    .B1(config_en),
    .B2(config_out[7]),
    .X(_024_)
  );
  sky130_fd_sc_hd__o22a_2 _071_ (
    .A1(_047_),
    .A2(\second_lut.mem[6] ),
    .B1(config_en),
    .B2(config_out[6]),
    .X(_023_)
  );
  sky130_fd_sc_hd__o22a_2 _072_ (
    .A1(_047_),
    .A2(\second_lut.mem[5] ),
    .B1(config_en),
    .B2(config_out[5]),
    .X(_022_)
  );
  sky130_fd_sc_hd__o22a_2 _073_ (
    .A1(_047_),
    .A2(\second_lut.mem[4] ),
    .B1(config_en),
    .B2(config_out[4]),
    .X(_021_)
  );
  sky130_fd_sc_hd__buf_1 _074_ (
    .A(_042_),
    .X(_048_)
  );
  sky130_fd_sc_hd__o22a_2 _075_ (
    .A1(_048_),
    .A2(\second_lut.mem[3] ),
    .B1(config_en),
    .B2(config_out[3]),
    .X(_020_)
  );
  sky130_fd_sc_hd__o22a_2 _076_ (
    .A1(_048_),
    .A2(\second_lut.mem[2] ),
    .B1(config_en),
    .B2(config_out[2]),
    .X(_019_)
  );
  sky130_fd_sc_hd__o22a_2 _077_ (
    .A1(_048_),
    .A2(\second_lut.mem[1] ),
    .B1(config_en),
    .B2(config_out[1]),
    .X(_018_)
  );
  sky130_fd_sc_hd__o22a_2 _078_ (
    .A1(_048_),
    .A2(\second_lut.mem[0] ),
    .B1(config_en),
    .B2(config_out[0]),
    .X(_017_)
  );
  sky130_fd_sc_hd__o22a_2 _079_ (
    .A1(_048_),
    .A2(\first_lut.mem[15] ),
    .B1(config_en),
    .B2(\second_lut.mem[7] ),
    .X(_016_)
  );
  sky130_fd_sc_hd__o22a_2 _080_ (
    .A1(\first_lut.mem[14] ),
    .A2(_044_),
    .B1(config_en),
    .B2(\second_lut.mem[6] ),
    .X(_015_)
  );
  sky130_fd_sc_hd__buf_1 _081_ (
    .A(_042_),
    .X(_041_)
  );
  sky130_fd_sc_hd__o22a_2 _082_ (
    .A1(_041_),
    .A2(\first_lut.mem[13] ),
    .B1(config_en),
    .B2(\second_lut.mem[5] ),
    .X(_014_)
  );
  sky130_fd_sc_hd__o22a_2 _083_ (
    .A1(_041_),
    .A2(\first_lut.mem[12] ),
    .B1(config_en),
    .B2(\second_lut.mem[4] ),
    .X(_013_)
  );
  sky130_fd_sc_hd__o22a_2 _084_ (
    .A1(_041_),
    .A2(\first_lut.mem[11] ),
    .B1(config_en),
    .B2(\second_lut.mem[3] ),
    .X(_012_)
  );
  sky130_fd_sc_hd__o22a_2 _085_ (
    .A1(_041_),
    .A2(\first_lut.mem[10] ),
    .B1(config_en),
    .B2(\second_lut.mem[2] ),
    .X(_011_)
  );
  sky130_fd_sc_hd__o22a_2 _086_ (
    .A1(_041_),
    .A2(\first_lut.mem[9] ),
    .B1(config_en),
    .B2(\second_lut.mem[1] ),
    .X(_010_)
  );
  sky130_fd_sc_hd__o22a_2 _087_ (
    .A1(_043_),
    .A2(\first_lut.mem[8] ),
    .B1(config_en),
    .B2(\second_lut.mem[0] ),
    .X(_009_)
  );
  sky130_fd_sc_hd__o22a_2 _088_ (
    .A1(_043_),
    .A2(\first_lut.mem[7] ),
    .B1(config_en),
    .B2(\first_lut.mem[15] ),
    .X(_040_)
  );
  sky130_fd_sc_hd__buf_2 _089_ (
    .A(config_out[0]),
    .X(\second_lut.mem[8] )
  );
  sky130_fd_sc_hd__buf_2 _090_ (
    .A(config_out[1]),
    .X(\second_lut.mem[9] )
  );
  sky130_fd_sc_hd__buf_2 _091_ (
    .A(config_out[2]),
    .X(\second_lut.mem[10] )
  );
  sky130_fd_sc_hd__buf_2 _092_ (
    .A(config_out[3]),
    .X(\second_lut.mem[11] )
  );
  sky130_fd_sc_hd__buf_2 _093_ (
    .A(config_out[4]),
    .X(\second_lut.mem[12] )
  );
  sky130_fd_sc_hd__buf_2 _094_ (
    .A(config_out[5]),
    .X(\second_lut.mem[13] )
  );
  sky130_fd_sc_hd__buf_2 _095_ (
    .A(config_out[6]),
    .X(\second_lut.mem[14] )
  );
  sky130_fd_sc_hd__buf_2 _096_ (
    .A(config_out[7]),
    .X(\second_lut.mem[15] )
  );
  sky130_fd_sc_hd__mux4_1 _097_ (
    .A0(\second_lut.mem[0] ),
    .A1(\second_lut.mem[1] ),
    .A2(\second_lut.mem[2] ),
    .A3(\second_lut.mem[3] ),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux4_1 _098_ (
    .A0(\second_lut.mem[4] ),
    .A1(\second_lut.mem[5] ),
    .A2(\second_lut.mem[6] ),
    .A3(\second_lut.mem[7] ),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux4_1 _099_ (
    .A0(config_out[0]),
    .A1(config_out[1]),
    .A2(config_out[2]),
    .A3(config_out[3]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux4_1 _100_ (
    .A0(config_out[4]),
    .A1(config_out[5]),
    .A2(config_out[6]),
    .A3(config_out[7]),
    .S0(addr[0]),
    .S1(addr[1]),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux4_1 _101_ (
    .A0(_000_),
    .A1(_001_),
    .A2(_007_),
    .A3(_008_),
    .S0(addr[2]),
    .S1(_006_),
    .X(out)
  );
  sky130_fd_sc_hd__mux4_1 _102_ (
    .A0(\first_lut.mem[0] ),
    .A1(\first_lut.mem[1] ),
    .A2(\first_lut.mem[2] ),
    .A3(\first_lut.mem[3] ),
    .S0(addr[3]),
    .S1(addr[4]),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux4_1 _103_ (
    .A0(\first_lut.mem[4] ),
    .A1(\first_lut.mem[5] ),
    .A2(\first_lut.mem[6] ),
    .A3(\first_lut.mem[7] ),
    .S0(addr[3]),
    .S1(addr[4]),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux4_1 _104_ (
    .A0(\first_lut.mem[8] ),
    .A1(\first_lut.mem[9] ),
    .A2(\first_lut.mem[10] ),
    .A3(\first_lut.mem[11] ),
    .S0(addr[3]),
    .S1(addr[4]),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux4_1 _105_ (
    .A0(\first_lut.mem[12] ),
    .A1(\first_lut.mem[13] ),
    .A2(\first_lut.mem[14] ),
    .A3(\first_lut.mem[15] ),
    .S0(addr[3]),
    .S1(addr[4]),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux4_1 _106_ (
    .A0(_002_),
    .A1(_003_),
    .A2(_004_),
    .A3(_005_),
    .S0(addr[5]),
    .S1(addr[6]),
    .X(_006_)
  );
  sky130_fd_sc_hd__dfxtp_2 _107_ (
    .CLK(config_clk),
    .D(_009_),
    .Q(\second_lut.mem[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _108_ (
    .CLK(config_clk),
    .D(_010_),
    .Q(\second_lut.mem[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _109_ (
    .CLK(config_clk),
    .D(_011_),
    .Q(\second_lut.mem[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _110_ (
    .CLK(config_clk),
    .D(_012_),
    .Q(\second_lut.mem[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _111_ (
    .CLK(config_clk),
    .D(_013_),
    .Q(\second_lut.mem[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _112_ (
    .CLK(config_clk),
    .D(_014_),
    .Q(\second_lut.mem[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _113_ (
    .CLK(config_clk),
    .D(_015_),
    .Q(\second_lut.mem[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _114_ (
    .CLK(config_clk),
    .D(_016_),
    .Q(\second_lut.mem[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _115_ (
    .CLK(config_clk),
    .D(_017_),
    .Q(config_out[0])
  );
  sky130_fd_sc_hd__dfxtp_2 _116_ (
    .CLK(config_clk),
    .D(_018_),
    .Q(config_out[1])
  );
  sky130_fd_sc_hd__dfxtp_2 _117_ (
    .CLK(config_clk),
    .D(_019_),
    .Q(config_out[2])
  );
  sky130_fd_sc_hd__dfxtp_2 _118_ (
    .CLK(config_clk),
    .D(_020_),
    .Q(config_out[3])
  );
  sky130_fd_sc_hd__dfxtp_2 _119_ (
    .CLK(config_clk),
    .D(_021_),
    .Q(config_out[4])
  );
  sky130_fd_sc_hd__dfxtp_2 _120_ (
    .CLK(config_clk),
    .D(_022_),
    .Q(config_out[5])
  );
  sky130_fd_sc_hd__dfxtp_2 _121_ (
    .CLK(config_clk),
    .D(_023_),
    .Q(config_out[6])
  );
  sky130_fd_sc_hd__dfxtp_2 _122_ (
    .CLK(config_clk),
    .D(_024_),
    .Q(config_out[7])
  );
  sky130_fd_sc_hd__dfxtp_2 _123_ (
    .CLK(config_clk),
    .D(_025_),
    .Q(\first_lut.mem[0] )
  );
  sky130_fd_sc_hd__dfxtp_2 _124_ (
    .CLK(config_clk),
    .D(_026_),
    .Q(\first_lut.mem[1] )
  );
  sky130_fd_sc_hd__dfxtp_2 _125_ (
    .CLK(config_clk),
    .D(_027_),
    .Q(\first_lut.mem[2] )
  );
  sky130_fd_sc_hd__dfxtp_2 _126_ (
    .CLK(config_clk),
    .D(_028_),
    .Q(\first_lut.mem[3] )
  );
  sky130_fd_sc_hd__dfxtp_2 _127_ (
    .CLK(config_clk),
    .D(_029_),
    .Q(\first_lut.mem[4] )
  );
  sky130_fd_sc_hd__dfxtp_2 _128_ (
    .CLK(config_clk),
    .D(_030_),
    .Q(\first_lut.mem[5] )
  );
  sky130_fd_sc_hd__dfxtp_2 _129_ (
    .CLK(config_clk),
    .D(_031_),
    .Q(\first_lut.mem[6] )
  );
  sky130_fd_sc_hd__dfxtp_2 _130_ (
    .CLK(config_clk),
    .D(_032_),
    .Q(\first_lut.mem[7] )
  );
  sky130_fd_sc_hd__dfxtp_2 _131_ (
    .CLK(config_clk),
    .D(_033_),
    .Q(\first_lut.mem[8] )
  );
  sky130_fd_sc_hd__dfxtp_2 _132_ (
    .CLK(config_clk),
    .D(_034_),
    .Q(\first_lut.mem[9] )
  );
  sky130_fd_sc_hd__dfxtp_2 _133_ (
    .CLK(config_clk),
    .D(_035_),
    .Q(\first_lut.mem[10] )
  );
  sky130_fd_sc_hd__dfxtp_2 _134_ (
    .CLK(config_clk),
    .D(_036_),
    .Q(\first_lut.mem[11] )
  );
  sky130_fd_sc_hd__dfxtp_2 _135_ (
    .CLK(config_clk),
    .D(_037_),
    .Q(\first_lut.mem[12] )
  );
  sky130_fd_sc_hd__dfxtp_2 _136_ (
    .CLK(config_clk),
    .D(_038_),
    .Q(\first_lut.mem[13] )
  );
  sky130_fd_sc_hd__dfxtp_2 _137_ (
    .CLK(config_clk),
    .D(_039_),
    .Q(\first_lut.mem[14] )
  );
  sky130_fd_sc_hd__dfxtp_2 _138_ (
    .CLK(config_clk),
    .D(_040_),
    .Q(\first_lut.mem[15] )
  );
endmodule
